name: Deploy Web to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH & Deploy Web
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/dominion/web
            git pull origin main
            bash deploy.sh
